# syntax = docker/dockerfile:1

FROM ruby:3.3.0

WORKDIR /usr/app

COPY Gemfile* .ruby-version ./

RUN apt-get update -qq && apt-get install -y postgresql-client cron
RUN bundle install

COPY . .

RUN whenever --update-crontab
